// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A personalized calorie calculation AI agent.
 *
 * - calculateCaloricNeeds - A function that handles the calorie calculation process.
 * - CaloricCalculationInput - The input type for the calculateCaloricNeeds function.
 * - CaloricCalculationOutput - The return type for the calculateCaloricNeeds function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CaloricCalculationInputSchema = z.object({
  gender: z.enum(['male', 'female']).describe('The gender of the user.'),
  age: z.number().describe('The age of the user in years.'),
  heightCm: z.number().describe('The height of the user in centimeters.'),
  weightKg: z.number().describe('The weight of the user in kilograms.'),
  activityLevel: z
    .enum(['sedentary', 'lightlyActive', 'moderatelyActive', 'veryActive', 'extraActive'])
    .describe('The activity level of the user.'),
  bodyFatPercentage: z.number().optional().describe('The body fat percentage of the user, if known.'),
  goal: z
    .enum(['weightLoss', 'muscleGain', 'maintainWeight'])
    .describe('The primary fitness goal of the user.'),
});
export type CaloricCalculationInput = z.infer<typeof CaloricCalculationInputSchema>;

const CaloricCalculationOutputSchema = z.object({
  tdee: z.number().describe('The calculated Total Daily Energy Expenditure (TDEE) in calories.'),
  proteinGrams: z.number().describe('The recommended daily protein intake in grams.'),
  fatGrams: z.number().describe('The recommended daily fat intake in grams.'),
  carbGrams: z.number().describe('The recommended daily carbohydrate intake in grams.'),
});
export type CaloricCalculationOutput = z.infer<typeof CaloricCalculationOutputSchema>;

export async function calculateCaloricNeeds(
  input: CaloricCalculationInput
): Promise<CaloricCalculationOutput> {
  return calculateCaloricNeedsFlow(input);
}

const calculateCaloricNeedsPrompt = ai.definePrompt({
  name: 'calculateCaloricNeedsPrompt',
  input: {schema: CaloricCalculationInputSchema},
  output: {schema: CaloricCalculationOutputSchema},
  prompt: `You are an expert nutrition advisor. Calculate the user's baseline caloric needs and macro targets based on their profile data, activity level, and body composition.

  Here's the user's information:
  Gender: {{{gender}}}
  Age: {{{age}}} years
  Height: {{{heightCm}}} cm
  Weight: {{{weightKg}}} kg
  Activity Level: {{{activityLevel}}}
  Body Fat Percentage: {{{bodyFatPercentage}}}%
  Goal: {{{goal}}}

  Calculate the Total Daily Energy Expenditure (TDEE) in calories. Then, determine the macro targets (protein, fat, and carbohydrates) in grams, optimized for their goal. Provide these values in JSON format.
`,
});

const calculateCaloricNeedsFlow = ai.defineFlow(
  {
    name: 'calculateCaloricNeedsFlow',
    inputSchema: CaloricCalculationInputSchema,
    outputSchema: CaloricCalculationOutputSchema,
  },
  async input => {
    const {output} = await calculateCaloricNeedsPrompt(input);
    return output!;
  }
);
