import type { ExerciseDefinition, ExerciseSubstitution } from './types';

export const EXERCISE_REGISTRY_VERSION = 1 as const;

export const EXERCISES: readonly ExerciseDefinition[] = [
  {
    id: 'bench-press', nameFa: 'پرس سینه هالتر', nameEn: 'Barbell bench press',
    aliasesFa: ['پرس سینه'], aliasesEn: ['bench press'], movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'anterior-deltoid'], equipment: ['barbell', 'bench'], difficulty: 'intermediate',
    contraindicationTags: ['shoulder_extension', 'elbow_load', 'wrist_extension', 'valsalva_risk'],
    videoSearchHints: { fa: ['آموزش فرم صحیح پرس سینه هالتر'], en: ['barbell bench press proper form'] },
  },
  {
    id: 'incline-db-press', nameFa: 'پرس بالاسینه دمبل', nameEn: 'Incline dumbbell press',
    aliasesFa: ['پرس بالا سینه دمبل'], aliasesEn: ['incline db press'], movementPattern: 'horizontal_push',
    primaryMuscles: ['upper-chest'], secondaryMuscles: ['triceps', 'anterior-deltoid'], equipment: ['dumbbell', 'bench'], difficulty: 'intermediate',
    contraindicationTags: ['shoulder_extension', 'shoulder_overhead', 'elbow_load', 'wrist_extension'],
    videoSearchHints: { fa: ['آموزش پرس بالاسینه دمبل'], en: ['incline dumbbell press proper form'] },
  },
  {
    id: 'shoulder-press', nameFa: 'پرس سرشانه دمبل', nameEn: 'Dumbbell shoulder press',
    aliasesFa: ['پرس سرشانه'], aliasesEn: ['dumbbell overhead press'], movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids'], secondaryMuscles: ['triceps'], equipment: ['dumbbell'], difficulty: 'intermediate',
    contraindicationTags: ['shoulder_overhead', 'elbow_load', 'wrist_extension', 'spinal_axial_load', 'valsalva_risk'],
    videoSearchHints: { fa: ['آموزش پرس سرشانه دمبل'], en: ['dumbbell shoulder press proper form'] },
  },
  {
    id: 'triceps-pushdown', nameFa: 'پشت بازو سیم‌کش', nameEn: 'Cable triceps pushdown',
    aliasesFa: ['پشت بازو کابل'], aliasesEn: ['triceps pushdown'], movementPattern: 'isolation',
    primaryMuscles: ['triceps'], secondaryMuscles: [], equipment: ['cable'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load'],
    videoSearchHints: { fa: ['آموزش پشت بازو سیم کش'], en: ['cable triceps pushdown proper form'] },
  },
  {
    id: 'lat-pulldown', nameFa: 'لت سیم‌کش', nameEn: 'Lat pulldown',
    aliasesFa: ['لت از بالا'], aliasesEn: ['cable lat pulldown'], movementPattern: 'vertical_pull',
    primaryMuscles: ['latissimus'], secondaryMuscles: ['biceps', 'upper-back'], equipment: ['cable'], difficulty: 'beginner',
    contraindicationTags: ['shoulder_overhead', 'elbow_load'],
    videoSearchHints: { fa: ['آموزش لت سیم کش فرم صحیح'], en: ['lat pulldown proper form'] },
  },
  {
    id: 'row', nameFa: 'قایقی سیم‌کش', nameEn: 'Seated cable row',
    aliasesFa: ['قایقی'], aliasesEn: ['cable row'], movementPattern: 'horizontal_pull',
    primaryMuscles: ['upper-back'], secondaryMuscles: ['latissimus', 'biceps'], equipment: ['cable'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load'],
    videoSearchHints: { fa: ['آموزش قایقی سیم کش'], en: ['seated cable row proper form'] },
  },
  {
    id: 'rear-delt', nameFa: 'نشر خم دمبل', nameEn: 'Bent-over rear-delt raise',
    aliasesFa: ['نشر خم'], aliasesEn: ['rear delt raise'], movementPattern: 'isolation',
    primaryMuscles: ['rear-deltoid'], secondaryMuscles: ['upper-back'], equipment: ['dumbbell'], difficulty: 'beginner',
    contraindicationTags: ['shoulder_extension', 'spinal_hinge'],
    videoSearchHints: { fa: ['آموزش نشر خم دمبل'], en: ['bent over rear delt raise form'] },
  },
  {
    id: 'curl', nameFa: 'جلو بازو دمبل', nameEn: 'Dumbbell curl',
    aliasesFa: ['جلو بازو'], aliasesEn: ['dumbbell biceps curl'], movementPattern: 'isolation',
    primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'], equipment: ['dumbbell'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load', 'wrist_extension'],
    videoSearchHints: { fa: ['آموزش جلو بازو دمبل'], en: ['dumbbell curl proper form'] },
  },
  {
    id: 'squat', nameFa: 'اسکوات هالتر', nameEn: 'Barbell back squat',
    aliasesFa: ['اسکوات'], aliasesEn: ['back squat', 'barbell squat'], movementPattern: 'squat',
    primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['hamstrings', 'core'], equipment: ['barbell'], difficulty: 'intermediate',
    contraindicationTags: ['knee_deep_flexion', 'knee_shear', 'spinal_axial_load', 'balance_demand', 'valsalva_risk'],
    videoSearchHints: { fa: ['آموزش اسکوات هالتر فرم صحیح'], en: ['barbell back squat proper form'] },
  },
  {
    id: 'rdl', nameFa: 'ددلیفت رومانیایی', nameEn: 'Romanian deadlift',
    aliasesFa: ['ددلیفت رومانیایی هالتر'], aliasesEn: ['rdl'], movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['back', 'forearms'], equipment: ['barbell'], difficulty: 'intermediate',
    contraindicationTags: ['spinal_hinge', 'valsalva_risk'],
    videoSearchHints: { fa: ['آموزش ددلیفت رومانیایی'], en: ['romanian deadlift proper form'] },
  },
  {
    id: 'leg-press', nameFa: 'پرس پا', nameEn: 'Leg press',
    aliasesFa: ['پرس پا دستگاه'], aliasesEn: ['machine leg press'], movementPattern: 'squat',
    primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['hamstrings'], equipment: ['full-gym'], difficulty: 'beginner',
    contraindicationTags: ['knee_deep_flexion', 'knee_shear', 'valsalva_risk'],
    videoSearchHints: { fa: ['آموزش پرس پا دستگاه'], en: ['leg press proper form'] },
  },
  {
    id: 'calf-raise', nameFa: 'ساق پا ایستاده', nameEn: 'Standing calf raise',
    aliasesFa: ['ساق پا'], aliasesEn: ['standing calf raise'], movementPattern: 'isolation',
    primaryMuscles: ['calves'], secondaryMuscles: [], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: ['balance_demand'],
    videoSearchHints: { fa: ['آموزش ساق پا ایستاده'], en: ['standing calf raise proper form'] },
  },
  {
    id: 'push-up', nameFa: 'شنا سوئدی', nameEn: 'Push-up',
    aliasesFa: ['شنا'], aliasesEn: ['pushup'], movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'anterior-deltoid'], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: ['shoulder_extension', 'elbow_load', 'wrist_extension'],
    videoSearchHints: { fa: ['آموزش شنا سوئدی فرم صحیح'], en: ['push up proper form'] },
  },
  {
    id: 'dumbbell-floor-press', nameFa: 'پرس سینه دمبل روی زمین', nameEn: 'Dumbbell floor press',
    aliasesFa: ['فلور پرس دمبل'], aliasesEn: ['dumbbell floor press'], movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'], secondaryMuscles: ['triceps'], equipment: ['dumbbell'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load', 'wrist_extension'],
    videoSearchHints: { fa: ['آموزش پرس سینه دمبل روی زمین'], en: ['dumbbell floor press proper form'] },
  },
  {
    id: 'half-kneeling-landmine-press', nameFa: 'پرس لندماین نیم‌زانو', nameEn: 'Half-kneeling landmine press',
    aliasesFa: ['پرس لندماین'], aliasesEn: ['landmine press'], movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids'], secondaryMuscles: ['chest', 'triceps'], equipment: ['landmine'], difficulty: 'beginner',
    contraindicationTags: ['shoulder_overhead', 'elbow_load'],
    videoSearchHints: { fa: ['آموزش پرس لندماین نیم زانو'], en: ['half kneeling landmine press form'] },
  },
  {
    id: 'band-triceps-extension', nameFa: 'پشت بازو با کش', nameEn: 'Band triceps extension',
    aliasesFa: ['پشت بازو کشی'], aliasesEn: ['band triceps pressdown'], movementPattern: 'isolation',
    primaryMuscles: ['triceps'], secondaryMuscles: [], equipment: ['bands'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load'],
    videoSearchHints: { fa: ['آموزش پشت بازو با کش'], en: ['band triceps extension form'] },
  },
  {
    id: 'band-row', nameFa: 'قایقی با کش', nameEn: 'Resistance-band row',
    aliasesFa: ['پارویی با کش'], aliasesEn: ['band row'], movementPattern: 'horizontal_pull',
    primaryMuscles: ['upper-back'], secondaryMuscles: ['latissimus', 'biceps'], equipment: ['bands'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load'],
    videoSearchHints: { fa: ['آموزش قایقی با کش'], en: ['resistance band row proper form'] },
  },
  {
    id: 'face-pull', nameFa: 'فیس پول', nameEn: 'Cable face pull',
    aliasesFa: ['فیس‌پول'], aliasesEn: ['face pull'], movementPattern: 'horizontal_pull',
    primaryMuscles: ['rear-deltoid', 'upper-back'], secondaryMuscles: ['rotator-cuff'], equipment: ['cable'], difficulty: 'beginner',
    contraindicationTags: ['shoulder_extension', 'elbow_load'],
    videoSearchHints: { fa: ['آموزش فیس پول'], en: ['cable face pull proper form'] },
  },
  {
    id: 'hammer-curl', nameFa: 'جلو بازو چکشی', nameEn: 'Hammer curl',
    aliasesFa: ['جلو بازو دمبل چکشی'], aliasesEn: ['dumbbell hammer curl'], movementPattern: 'isolation',
    primaryMuscles: ['biceps', 'brachialis'], secondaryMuscles: ['forearms'], equipment: ['dumbbell'], difficulty: 'beginner',
    contraindicationTags: ['elbow_load'],
    videoSearchHints: { fa: ['آموزش جلو بازو چکشی'], en: ['hammer curl proper form'] },
  },
  {
    id: 'box-squat', nameFa: 'اسکوات روی جعبه با وزن بدن', nameEn: 'Bodyweight box squat',
    aliasesFa: ['باکس اسکوات'], aliasesEn: ['bodyweight box squat'], movementPattern: 'squat',
    primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: ['knee_deep_flexion', 'knee_shear', 'balance_demand'],
    videoSearchHints: { fa: ['آموزش باکس اسکوات وزن بدن'], en: ['bodyweight box squat proper form'] },
  },
  {
    id: 'glute-bridge', nameFa: 'پل باسن', nameEn: 'Glute bridge',
    aliasesFa: ['بریج باسن'], aliasesEn: ['bodyweight glute bridge'], movementPattern: 'hinge',
    primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings', 'core'], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: [],
    videoSearchHints: { fa: ['آموزش پل باسن فرم صحیح'], en: ['glute bridge proper form'] },
  },
  {
    id: 'reverse-lunge', nameFa: 'لانج معکوس', nameEn: 'Reverse lunge',
    aliasesFa: ['لانگز معکوس'], aliasesEn: ['reverse lunge'], movementPattern: 'lunge',
    primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: ['knee_deep_flexion', 'knee_shear', 'balance_demand'],
    videoSearchHints: { fa: ['آموزش لانج معکوس'], en: ['reverse lunge proper form'] },
  },
  {
    id: 'seated-calf-raise', nameFa: 'ساق پا نشسته', nameEn: 'Seated calf raise',
    aliasesFa: ['ساق نشسته'], aliasesEn: ['seated calf raise'], movementPattern: 'isolation',
    primaryMuscles: ['calves'], secondaryMuscles: [], equipment: ['bodyweight'], difficulty: 'beginner',
    contraindicationTags: [],
    videoSearchHints: { fa: ['آموزش ساق پا نشسته'], en: ['seated calf raise proper form'] },
  },
] as const;

export const EXERCISE_SUBSTITUTIONS: readonly ExerciseSubstitution[] = [
  { sourceId: 'bench-press', substituteId: 'push-up', reason: 'equipment', priority: 1 },
  { sourceId: 'bench-press', substituteId: 'dumbbell-floor-press', reason: 'joint_friendly', priority: 2 },
  { sourceId: 'incline-db-press', substituteId: 'push-up', reason: 'equipment', priority: 1 },
  { sourceId: 'shoulder-press', substituteId: 'half-kneeling-landmine-press', reason: 'joint_friendly', priority: 1 },
  { sourceId: 'triceps-pushdown', substituteId: 'band-triceps-extension', reason: 'equipment', priority: 1 },
  { sourceId: 'row', substituteId: 'band-row', reason: 'equipment', priority: 1 },
  { sourceId: 'rear-delt', substituteId: 'face-pull', reason: 'same_pattern', priority: 1 },
  { sourceId: 'curl', substituteId: 'hammer-curl', reason: 'joint_friendly', priority: 1 },
  { sourceId: 'squat', substituteId: 'box-squat', reason: 'skill_regression', priority: 1 },
  { sourceId: 'squat', substituteId: 'glute-bridge', reason: 'joint_friendly', priority: 2 },
  { sourceId: 'leg-press', substituteId: 'box-squat', reason: 'equipment', priority: 1 },
  { sourceId: 'leg-press', substituteId: 'glute-bridge', reason: 'joint_friendly', priority: 2 },
  { sourceId: 'calf-raise', substituteId: 'seated-calf-raise', reason: 'joint_friendly', priority: 1 },
] as const;
